#!/bin/bash

args=("$@")
# Use the provided folder path and delay time
DELAY=${args[-2]}
OPTION=${args[-1]}
unset args[-2]
unset args[-1]

IMAGE_DIR=${args[*]}
echo "Image directory: $args"
echo "Delay: $DELAY"
echo "Option: $OPTION"

restore_kitty_config() {
    if [ -n "$KITTY_WINDOW_ID" ]; then
        kitten @ load-config -o window_padding_width=25
    fi
}
trap restore_kitty_config EXIT

if [ -n "$KITTY_WINDOW_ID" ]; then
    kitten @ load-config -o window_padding_width=0
fi

if OPTION=="-r"
then
  chafa $(ls $IMAGE_DIR | shuf) --clear --scale max --align mid,mid -d $DELAY &
else
  chafa $IMAGE_DIR --clear --scale max --align mid,mid -d $DELAY &
fi

wait
